workflows:
  android_release:
    name: Android Release Build
    max_build_duration: 120  # 最大构建时长（分钟）
    environment:
      flutter: stable  # 使用 Flutter 的稳定版（如果是 Flutter 项目）
    scripts:
      - name: Install dependencies
        script: |
          git submodule update --init --recursive
          ./gradlew clean
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # 指定生成的 APK 文件路径