workflows:
  android_release:
    name: Android Release Build
    max_build_duration: 120  # 最大构建时长（分钟）
    environment:
      flutter: stable  # 使用 Flutter 稳定版本
    scripts:
      - name: Install dependencies
        script: |
          git submodule update --init --recursive
          ./gradlew clean
          ./gradlew build --stacktrace --info  # 使用调试信息帮助定位错误
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease --stacktrace --info
    android:
      api_level: 30  # 使用 API Level 30 (例如：Android 11)
    artifacts:
      - app/build/outputs/apk/release/app-release.apk  # 保存构建的 APK
